cygnus_olytics_default:
    pattern: /
    defaults: { _controller: CygnusOlyticsBundle:Default:index }

cygnus_olytics_event_tracker:
    pattern:  /events/{account}/{product}
    defaults: { _controller: CygnusOlyticsBundle:Event:index }

cygnus_olytics_backsync_db9:
    pattern:  /backsync/db9
    defaults: { _controller: CygnusOlyticsBundle:Backsync:index }

cygnus_olytics_merge:
    pattern:  /merge
    defaults: { _controller: CygnusOlyticsBundle:Merge:index }

cygnus_olytics_library:
    pattern:  /olytics.js
    defaults: { _controller: CygnusOlyticsBundle:Js:index }

cygnus_olytics_test_request:
    pattern:  /test
    defaults: { _controller: CygnusOlyticsBundle:Test:index }
