cygnus_olytics_default:
    pattern: /
    defaults: { _controller: CygnusOlyticsBundle:Default:index }

cygnus_olytics_event_tracker:
    pattern:  /events/{account}/{product}
    defaults: { _controller: CygnusOlyticsBundle:Event:index }

cygnus_olytics_library:
    pattern:  /olytics.js
    defaults: { _controller: CygnusOlyticsBundle:Js:index }

cygnus_olytics_test_request:
    pattern:  /test
    defaults: { _controller: CygnusOlyticsBundle:Test:index }

cygnus_olytics_conversion_userid:
    pattern:  /conversion/userids
    defaults: { _controller: CygnusOlyticsBundle:Conversion:appendUserIds }

cygnus_olytics_conversion_events:
    pattern:  /conversion/events
    defaults: { _controller: CygnusOlyticsBundle:Conversion:appendUserIdsToEvents }