cygnus_olytics_default:
    pattern: /
    defaults: { _controller: CygnusOlyticsBundle:Default:index }

cygnus_olytics_sapience:
    pattern: /sapience
    defaults: { _controller: CygnusOlyticsBundle:Default:sapience }

cygnus_olytics_event_tracker:
    pattern:  /events/{account}/{product}
    defaults: { _controller: CygnusOlyticsBundle:Event:index }

cygnus_olytics_library:
    pattern:  /olytics.js
    defaults: { _controller: CygnusOlyticsBundle:Js:index }

cygnus_sapience_library:
    pattern:  /sapience.js
    defaults: { _controller: CygnusOlyticsBundle:Js:sapience }

cygnus_olytics_test_request:
    pattern:  /test
    defaults: { _controller: CygnusOlyticsBundle:Test:index }
